// Code generated by "stringer -type=Heuristic"; DO NOT EDIT.

package heuristic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Euclidean-0]
	_ = x[Manhattan-1]
}

const _Heuristic_name = "EuclideanManhattan"

var _Heuristic_index = [...]uint8{0, 9, 18}

func (i Heuristic) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Heuristic_index)-1 {
		return "Heuristic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Heuristic_name[_Heuristic_index[idx]:_Heuristic_index[idx+1]]
}
